services:
  n8n:
    image: n8nio/n8n:stable
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    env_file: .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8npostgres
      POSTGRES_DB: n8n
    volumes:
      - ./postgres_data:/var/lib/postgressql/data

volumes:
  n8n_data:
  postgres_data:

      
